apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQK  # Base64 kodowane "password"
  user: c3R1ZGVudA==           # Base64 kodowane "student"
  password: cGFzc3dvcmQxMjM=   # Base64 kodowane "password123"

